TITLE			:=	wIRC
ID				:=	org.webosinternals.wirc
VERSION         :=	2.99.20100603
VENDOR			:=	webOS-Internals
VENDOR_EMAIL	:=	support@webos-internals.org
VENDOR_URL		:=	http://www.webos-internals.org/wiki/Application:WIRC

PLUGIN			:=	wirc
MEM_USAGE		:=	1

PLUGIN_DIR		:= 	src

APPINFO			:=	appinfo.json