#!/bin/sh                                                                                       

PID="org.webosinternals.wirc"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the old application
if [ -f $APPS/usr/lib/ipkg/info/ws.junk.wirc.prerm ] ; then
  IPKG_OFFLINE_ROOT=$APPS sh $APPS/usr/lib/ipkg/info/ws.junk.wirc.prerm || true
fi
/usr/bin/ipkg -o $APPS -force-depends remove ws.junk.wirc || true

# Remove the obsolete daemon
if [ -f $APPS/usr/lib/ipkg/info/us.ryanhope.wircd.prerm ] ; then
  IPKG_OFFLINE_ROOT=$APPS sh $APPS/usr/lib/ipkg/info/us.ryanhope.wircd.prerm || true
fi
/usr/bin/ipkg -o $APPS -force-depends remove us.ryanhope.wircd || true

# Stop any existing service
/sbin/stop ${PID} || true
killall -9 ${PID} || true

# Install the upstart script
rm -f /etc/event.d/${PID}
cp $IPKG_OFFLINE_ROOT/usr/palm/applications/${PID}/upstart/${PID} /etc/event.d/${PID}

# Copy executable outside of encrypted mount
mkdir -p /var/usr/sbin/
rm -f /var/usr/sbin/${PID}
install -m 755 $IPKG_OFFLINE_ROOT/usr/palm/applications/${PID}/bin/${PID} /var/usr/sbin/${PID}

# Start the service
/sbin/start ${PID}

exit 0
