#!/bin/sh

PID="org.webosinternals.wirc"

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

# Stop any existing service
/sbin/stop ${PID} || true
killall -9 ${PID} || true

# Remove the upstart script
rm -f /etc/event.d/${PID}

# Remove the exec
rm -f /var/usr/sbin/${PID}

exit 0
